### ISSUE TITLE
Question: `compose` and `assoc` to build a structure

### ISSUE THREAD

**Issue by knikel** [donnut/typescript-ramda#101]
Hi folks, this is a question rather than an issue. I'm somewhat new to the wonders of ramda and TypeScript and I might have a naive question here, so please bear with me 😉 

I'm trying to build an object that matches a given interface through `compose` and mutliple `assoc`s, something like

```
interface SomeStruct {
  a: number[];
  b: string[];
  c: { [index: string]: string };
}

const x: SomeStruct = {
  'a': [],
  'b': [],
  'c': {},
};

const fun = (y: SomeStruct): SomeStruct => {
  return compose(
    assoc('a', [1, 2, 3]),
    assoc('b', ['a', 'b', 'c']),
    assoc('c', { 'k': 'v'})
  )(y);
};

fun(x);
```

Doing this, I'm getting a following error:

```
error TS2322: Type '{ prop: number[]; } & {}' is not assignable to type 'SomeStruct'.
Property 'a' is missing in type '{ prop: number[]; } & {}'
```

The effective and intermediate structure of x matches the `SomeType` at all steps of this function application. Is there some way around it besides using `as any` after `compose`? Am I missing something pretty basic here?

---

Edit: Sorry, now I see it might be related to #90

**Comment by whitecolor** [comment]
`{ prop: number[]; } ` is wrong, `assoc` has really not working typings, should be fixed.

**Comment by tycho01** [comment]
If this turns out not be a duplicate when #90 is resolved, let's reopen.

**Comment by tycho01** [comment]
So I fixed #90; guess what, your test isn't passing yet. So reopening until your test passes, as promised. :)

**Comment by tycho01** [comment]
Well, now we know. This wasn't an `assoc` issue, but a composition one.

It stems from interaction between composition and functions with generics. Threads [#92](https://github.com/donnut/typescript-ramda/issues/92) and [#86](https://github.com/donnut/typescript-ramda/issues/86) appeared to be about the same problem. I currently intend to track this issue in [#78](https://github.com/donnut/typescript-ramda/issues/78), about currying rather than composition but otherwise seemingly the same issue.

Sorry you're getting bounced to yet another thread again. I'm slowly discovering most outstanding issues are highly related though, so hopefully if I can figure this out we'll have solved everything in one go.

**Comment by knikel** [comment]
No worries @tycho01. Thanks a lot for the time you've put into looking into that!
