### ISSUE TITLE
use TS type guards over `: boolean` in type check functions (R.is, R.is[X])

### ISSUE THREAD

**Issue by tycho01** [donnut/typescript-ramda#109]
We now have e.g. `is(ctor: any, val: any): boolean;`, which the TS docs tell us we can further strengthen using [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html). Let's do that. :)

Edit: on second thought, I don't think at the type level we get enough information to better type the other is functions, beside the generic one...

**Comment by TylerYang** [comment]
Could sombody take a look at this mr, please? I just meet a use case that might need to merge this mr, 

``` javascript
function grepSomethingRecursively(grepPatterns: String | String[]) {
    if (R.is(Array, grepPatterns)) {
        R.forEach(doSomething, grepPatterns) 
        //throw exception: argument of type 'string | string[]' is not assignable to parameter of type 'string[]'.
    } else {
        ...
    }
}
```

`R.forEach` is required to take array as its parameters.
And with running `R.is` the type of `grepPatterns` cannot be inferred by the checker. So it throw an exception. 

In contrast, the `lodash` works fine due to [the definition.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L11591)

**Comment by TylerYang** [comment]
Hi @tycho01 ,I just copy your mr and try to run with this function,  it throws the exception also.

`//throw exception: argument of type 'string | string[]' is not assignable to parameter of type 'string[]'.`

**Comment by tycho01** [comment]
@TylerYang: thanks for reporting this! I just merged in your use-case as a new test and implemented a [fix](https://github.com/donnut/typescript-ramda/pull/114/commits/dacb14793a4d5249091fea27146cc13d2315362f).

**Comment by TylerYang** [comment]
NP : )
