### ISSUE TITLE
Definitely-Typed depreciation

### ISSUE THREAD

**Issue by enriched** [donnut/typescript-ramda#50]
First off, thank you for these fantastic typings and happy to see that there is recent activity on this.

Because my team moved off of definitely typed on on to the newer [typings](https://github.com/typings/typings) I created a copy of these typings at https://github.com/enriched/typed-ramda that I could hack on.  I have added/corrected some functionality there as well, just on an as needed basis.

I am wondering if you want to combine efforts on this somehow though.  I don't know if we can have both the ambient and typings definitions in the same place, but I definitely don't want to be missing out on your fixes or vice-versa.

**Comment by donnut** [comment]
I haven't really looked into the way how to distribute `typescript-ramda`, but I like the `typings` approach better because no seperate copy into another repo (DefinitelyTyped) is necessary. It there any change necessary to get `typescript-ramda` compabile with `typings`.

I love to join efforts and avoid duplicates. If we need to make a change to `typescript-ramda` so that it works for you/`typings`, please let me know.

**Comment by donnut** [comment]
@enriched still interested in some kind of collaboration? Otherwise I'll close this issue. 
Thanks!

**Comment by enriched** [comment]
Sorry about the long response time, I really need to tune my github notifications.  From a recent [pull request](https://github.com/enriched/typed-ramda/pull/2) that I had, I think that @blakeembrey is going to fork my repository into [typed-typings](https://github.com/typed-typings) and have that org manage the pull requests.  

Unfortunately I have too much on my plate right now to be able to get to anything fast enough 😢

**Comment by donnut** [comment]
@enriched no problem for your late reponse. 

I appreciate that you have your own fork of this repo and that you tune it to your needs, but I would appreciate it if references from typings/register and typed-typings maintained by @blakeembrey refer to the original repo donnut/typescript-ramda. Otherwise it will be confusion for users which repo to use. 

Thanks!

**Comment by blakeembrey** [comment]
@donnut The definition here can't be consumed properly by Typings - they need to be in external module format. I'm happy to correct references if you intend to maintain it, but it needs to be in the correct format for people to use first. If you make that change, feel free to open a PR to the Typings registry.

**Comment by donnut** [comment]
I've made the necessary changes and create a PR on typings/registry

**Comment by blakeembrey** [comment]
Thanks @donnut. I just started using Ramda with this definition 😄

**Comment by donnut** [comment]
:+1:
