### ISSUE TITLE
assoc typing issue

### ISSUE THREAD

**Issue by whitecolor** [donnut/typescript-ramda#90]
`assoc<T,U>(prop: string, val: T, obj: U): {prop: T} & U;`

`{prop: T}` ? Unfortunately TS is not ready not handle such case with dynamic typing yet.

https://github.com/Microsoft/TypeScript/issues/1295

**Comment by whitecolor** [comment]
Following https://gist.github.com/donnut/fd56232da58d25ceecf1

`assoc(prop: string)` too requires use kind of `CurriedFunction` interface in signature, but this:
```ts
    interface CurriedFunction2<T1, T2, R> {
        (t1: T1): (t2: T2) => R;
        (t1: T1, t2: T2): R;
    }
```
seem not will work for this case, but this:
```ts
    interface CurriedFunction2WithoutTypeParams {
        <T1, T2, R>(t1: T1, t2: T2): R;
        <T1>(t1: T1): <T2, R>(t2: T2) => R;        
    }
```
should work
```ts
assoc(prop: string): CurriedFunction2WithoutTypeParams
```
@donnut what do you think about this issue?

**Comment by tycho01** [comment]
Thanks. It seems most of the remaining issues concern currying/composition, and this suggestion might address a key part of that. I'll try to update the definitions based on this.

**Comment by tycho01** [comment]
I tried adding all of the outstanding issues as tests, and manually tried your suggested typings to see how it would affect the results.
Outcome: the suggested change solves your case (other open issues appear unrelated), but breaks some old tests. It appears that adding your suggested version in addition to (-> after, not before) the original version addresses both your case and the otherwise broken tests.
I'll update the script and make a PR.

**Comment by whitecolor** [comment]
Ok, thanks, will see how it will work out.

**Comment by tycho01** [comment]
By now, #73 pushed me in the opposite direction, showing that redefined generics are in fact bug rather than feature. I've now re-diagnosed your actual issue, and it does in fact seem to be the same problem about generics within curried functions as reported in #78, and I suppose the composition-related ones #86, #92, and #101.
I'll revert the earlier work-around, and will try to look for a proper fix along with those other issues.
